/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tienda;

import java.awt.print.Printable;
import java.awt.*;
import java.awt.print.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Factura extends javax.swing.JFrame implements Printable {

    tiendita tiendita = new tiendita();

    DefaultTableModel mdlTabla;

    public Factura() {
        initComponents();

        this.setTitle("TIENDITA MINORISTA");

        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/tienda.png"));
        Image logo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/tienda.png"));
        lblLogo.setIcon(new ImageIcon(icono.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH)));

        this.setIconImage(icono);

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recibo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_dni = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_Imprimiir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_Nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_mediopago = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_SubTotal = new javax.swing.JLabel();
        lbl_Igv = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recibo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        recibo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Comprobante de pago.......................");
        recibo.add(jLabel1);
        jLabel1.setBounds(40, 40, 330, 25);

        lbl_dni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_dni.setText("...................");
        recibo.add(lbl_dni);
        lbl_dni.setBounds(130, 130, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("DNI:");
        recibo.add(jLabel3);
        jLabel3.setBounds(40, 130, 80, 30);

        tblProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Productos", "Precio.Uni", "Precio.Cant"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setMaxWidth(40);
            tblProductos.getColumnModel().getColumn(2).setMaxWidth(70);
            tblProductos.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        recibo.add(jScrollPane1);
        jScrollPane1.setBounds(30, 180, 480, 140);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Gracias por su Preferencia......//");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(40, 40, 40))
        );

        recibo.add(jPanel1);
        jPanel1.setBounds(40, 400, 480, 110);

        btn_Imprimiir.setText("Imprimir");
        btn_Imprimiir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimiirActionPerformed(evt);
            }
        });
        recibo.add(btn_Imprimiir);
        btn_Imprimiir.setBounds(435, 523, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cliente:");
        recibo.add(jLabel5);
        jLabel5.setBounds(40, 100, 60, 30);

        lbl_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Nombre.setText(".................");
        recibo.add(lbl_Nombre);
        lbl_Nombre.setBounds(130, 100, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Medio de pago: ");
        recibo.add(jLabel2);
        jLabel2.setBounds(260, 370, 110, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Subtotal: ");
        recibo.add(jLabel6);
        jLabel6.setBounds(40, 340, 70, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Igv:");
        recibo.add(jLabel7);
        jLabel7.setBounds(40, 370, 70, 14);

        lbl_mediopago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_mediopago.setText("..........");
        recibo.add(lbl_mediopago);
        lbl_mediopago.setBounds(400, 370, 130, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Total:");
        recibo.add(jLabel9);
        jLabel9.setBounds(260, 340, 70, 14);

        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_total.setText("..........");
        recibo.add(lbl_total);
        lbl_total.setBounds(400, 340, 110, 14);

        lbl_SubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_SubTotal.setText("............");
        recibo.add(lbl_SubTotal);
        lbl_SubTotal.setBounds(130, 340, 100, 14);

        lbl_Igv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Igv.setText(".............");
        recibo.add(lbl_Igv);
        lbl_Igv.setBounds(130, 370, 90, 14);

        lblLogo.setText("jLabel8");
        recibo.add(lblLogo);
        lblLogo.setBounds(370, 70, 130, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recibo, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recibo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        recibo.getAccessibleContext().setAccessibleName("f");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ImprimiirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimiirActionPerformed
        try {
            PrinterJob gap = PrinterJob.getPrinterJob();
            gap.setPrintable(this);
            boolean top = gap.printDialog();

            if (top) {
                gap.print();
            }
        } catch (PrinterException pex) {
            JOptionPane.showMessageDialog(null, "ERROR DE PROGRAMA", "Error\n" + pex, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_ImprimiirActionPerformed

    String nombre;
    String dni;
    String mediopago;
    public void DatosComprador(String nombre, String dni, String mediopago) {
        this.nombre = nombre;
        lbl_Nombre.setText(nombre);
        
        this.dni = dni;
        lbl_dni.setText(dni);
        
        this.mediopago = mediopago;
        lbl_mediopago.setText(mediopago);

    }

    //Dar formato moneda
    public String aMoneda(double precio) {
        return "S/. " + Math.round(precio * 100.0) / 100.0;
    }
    DefaultTableModel modelo3 = new DefaultTableModel();
    double subtotal;
    double iva;
    double total;

    public void TablaFactura(double subtotal, double iva, double total, DefaultTableModel modelo2) {

        this.subtotal = subtotal;
        lbl_SubTotal.setText(aMoneda(subtotal));

        this.iva = iva;
        lbl_Igv.setText(aMoneda(iva));

        this.total = total;
        lbl_total.setText(aMoneda(total));

        this.modelo3 = modelo2;
        tblProductos.setModel(modelo3);
       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Imprimiir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lbl_Igv;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_SubTotal;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_mediopago;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JPanel recibo;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
        if (index > 0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D hub = (Graphics2D) graf;
        hub.translate(pagfor.getImageableX() + 30, pagfor.getImageableY() + 30);
        hub.scale(1.0, 1.0);

        recibo.printAll(graf);
        return PAGE_EXISTS;

    }
}
